using PaddleOcrSharp.Formats.Gguf;
using PaddleOcrSharp.Quantization;

namespace PaddleOcrSharp.Tests.Quantization;

/// <summary>
/// The ternary block layouts, against the C reference they are transcribed from and against each
/// other.
/// </summary>
public class TernaryCodecTests
{
    /// <summary>
    /// Bytes <c>quantize_row_pq2_0_ref</c> produces for <c>w[i] = sin(i)</c> over two blocks.
    /// </summary>
    /// <remarks>
    /// Generated by compiling the two reference encoders out of the PrismML fork's
    /// <c>ggml/src/ggml-quants.c</c> and feeding them this input. The input is a formula rather
    /// than a fixture file so the vector is reproducible from the test alone, and the expectation
    /// is a literal so a change to our encoder cannot quietly change what "correct" means.
    /// </remarks>
    private const string ExpectedPq20 =
        "003C699006A4411AA4416A9006699006A4411AA4416A9006699006A4411AA4415A90FE3B06699006A5411AA4415A"
        + "9006699006A5411AA4415A9006699006A5411AA4411A";

    /// <summary>Bytes <c>quantize_row_ptq1_0_ref</c> produces for the same input.</summary>
    private const string ExpectedPtq10 =
        "87C0C282403E7EC0BF7F40412C6BC0D5334491CDB366334DCBCE003CD579404787C0B982403E7EC0C27F4041E9CD"
        + "676F334491CD6C30FE3B";

    [Fact]
    public void Pq20EncodingMatchesTheReference()
    {
        float[] weights = Sine(256);
        byte[] packed = new byte[2 * TernaryBlockGeometry.Pq20BlockBytes];

        TernaryBlocks.EncodePq20(weights, packed);

        Assert.Equal(ExpectedPq20, Convert.ToHexString(packed));
    }

    [Fact]
    public void Ptq10EncodingMatchesTheReference()
    {
        float[] weights = Sine(256);
        byte[] packed = new byte[2 * TernaryBlockGeometry.Ptq10BlockBytes];

        TernaryBlocks.EncodePtq10(weights, packed);

        Assert.Equal(ExpectedPtq10, Convert.ToHexString(packed));
    }

    [Fact]
    public void BlockSizesAreTheAdvertisedBitRates()
    {
        Assert.Equal(34, TernaryBlockGeometry.Pq20BlockBytes);
        Assert.Equal(28, TernaryBlockGeometry.Ptq10BlockBytes);
        Assert.Equal(2.125, TernaryBlockGeometry.Pq20BlockBytes * 8.0 / TernaryBlockGeometry.GroupSize);
        Assert.Equal(1.75, TernaryBlockGeometry.Ptq10BlockBytes * 8.0 / TernaryBlockGeometry.GroupSize);
    }

    [Theory]
    [InlineData(GgmlType.PQ2_0)]
    [InlineData(GgmlType.PTQ1_0)]
    public void TernaryInputSurvivesTheRoundTrip(GgmlType type)
    {
        // An already-ternary group is the case the container was built for: the scale is exactly
        // the group's amax, so the only loss is the fp16 the scale is stored in.
        var random = new Random(11);
        const float Scale = 0.0371f;
        float[] weights = new float[512];
        for (int i = 0; i < weights.Length; i++)
        {
            weights[i] = (random.Next(3) - 1) * Scale;
        }

        byte[] packed = new byte[type.RowSize(weights.Length)];
        float[] decoded = new float[weights.Length];

        TernaryBlocks.Encode(type, weights, packed);
        TernaryBlocks.Decode(type, packed, decoded);

        // The scale is the only thing that can move: fp16 has eleven significant bits, so the
        // decoded magnitude is within one part in a thousand of the original and the trit is exact.
        float tolerance = (MathF.Abs(Scale) * 1e-3f) + 1e-9f;

        for (int i = 0; i < weights.Length; i++)
        {
            Assert.Equal(weights[i], decoded[i], tolerance);
            Assert.Equal(MathF.Sign(weights[i]), MathF.Sign(decoded[i]));
        }
    }

    [Theory]
    [InlineData(GgmlType.PQ2_0)]
    [InlineData(GgmlType.PTQ1_0)]
    public void TheVectorKernelAgreesWithTheReferenceExactly(GgmlType type)
    {
        var random = new Random(23);
        float[] weights = new float[128 * 16];
        for (int i = 0; i < weights.Length; i++)
        {
            weights[i] = (float)((random.NextDouble() * 2) - 1);
        }

        byte[] packed = new byte[type.RowSize(weights.Length)];
        TernaryBlocks.Encode(type, weights, packed);

        float[] reference = new float[weights.Length];
        float[] vectorised = new float[weights.Length];
        TernaryBlocks.Decode(type, packed, reference);
        TernaryKernels.DecodeRow(type, packed, vectorised);

        // Not "close": the vector kernel is the same integer arithmetic, so any difference is a
        // transcription error rather than a rounding one.
        Assert.Equal(reference, vectorised);
    }

    [Theory]
    [InlineData(GgmlType.PQ2_0)]
    [InlineData(GgmlType.PTQ1_0)]
    public void AnAllZeroGroupDecodesToZero(GgmlType type)
    {
        float[] weights = new float[128];
        byte[] packed = new byte[type.RowSize(weights.Length)];
        float[] decoded = new float[weights.Length];

        TernaryBlocks.Encode(type, weights, packed);
        TernaryBlocks.Decode(type, packed, decoded);

        Assert.All(decoded, value => Assert.Equal(0f, value));
    }

    [Fact]
    public void AShortRowIsRejectedRatherThanTruncated()
    {
        float[] weights = new float[100];
        byte[] packed = new byte[64];

        Assert.Throws<ArgumentException>(() => TernaryBlocks.EncodePq20(weights, packed));
    }

    private static float[] Sine(int count)
    {
        float[] values = new float[count];
        for (int i = 0; i < count; i++)
        {
            values[i] = (float)Math.Sin(i);
        }

        return values;
    }
}
