<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PaddleOcrSharp</RootNamespace>
    <AssemblyName>PaddleOcrSharp</AssemblyName>
    <IsPackable>true</IsPackable>
    <PackageId>PaddleOcrSharp</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.0" />
    <PackageReference Include="System.Numerics.Tensors" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

</Project>
