"""Re-derives the ternary block layouts from the PrismML llama.cpp fork's C.

Unlike the rest of this directory this script needs no checkpoint and no model: it is a
transcription of `quantize_row_pq2_0_ref`, `quantize_row_ptq1_0_ref` and `dequantize_row_ptq1_0`
from `ggml/src/ggml-quants.c` in https://github.com/PrismML-Eng/llama.cpp, and it exists so the
golden vectors in `TernaryCodecTests` can be regenerated by someone who does not want to compile
llama.cpp to check them.

Two details decide whether a transcription is right, and both are silent when wrong:

- C's `roundf`/`lroundf` round halves away from zero. NumPy's `round` and .NET's `MathF.Round`
  round halves to even, which is a one-code difference on an exact half.
- The base-3 area does not store the base-3 value. It stores `ceil(v * 256 / 243)`, which lets the
  decoder recover digit `n` as `((byte * 3**n) & 0xFF) * 3 >> 8` — a multiply and a shift instead
  of a division.

    python dump_ternary_blocks.py            # the vectors the C# test asserts
    python dump_ternary_blocks.py --blocks 8 # more of them
"""

from __future__ import annotations

import argparse
import math
import struct

GROUP = 128
PQ2_0_BYTES = 2 + GROUP // 4
PTQ1_0_LOW = (GROUP - 4 * GROUP // 64) // 5
PTQ1_0_HIGH = GROUP // 64
PTQ1_0_BYTES = PTQ1_0_LOW + PTQ1_0_HIGH + 2
STAGES = (32, 16, 8)


def round_half_away(value: float) -> int:
    """C's `roundf`: halves go away from zero, not to even."""
    return int(math.floor(value + 0.5)) if value >= 0 else int(math.ceil(value - 0.5))


def fp16(value: float) -> bytes:
    return struct.pack("<e", value)


def encode_pq2_0(weights: list[float]) -> bytes:
    out = bytearray()
    for base in range(0, len(weights), GROUP):
        group = weights[base : base + GROUP]
        scale = max(abs(w) for w in group)
        inverse = 1.0 / scale if scale > 0 else 0.0
        codes = bytearray(GROUP // 4)
        for j, w in enumerate(group):
            q = min(3, max(0, round_half_away(w * inverse) + 1))
            codes[j // 4] |= q << ((j % 4) * 2)
        out += fp16(scale) + codes
    return bytes(out)


def encode_ptq1_0(weights: list[float]) -> bytes:
    out = bytearray()
    for base in range(0, len(weights), GROUP):
        group = weights[base : base + GROUP]
        scale = max(abs(w) for w in group)
        inverse = 1.0 / scale if scale > 0 else 0.0

        low = bytearray(PTQ1_0_LOW)
        high = bytearray(PTQ1_0_HIGH)

        read = 0
        j = 0
        for stage in STAGES:
            while j + stage <= PTQ1_0_LOW:
                for m in range(stage):
                    value = 0
                    for n in range(5):
                        trit = round_half_away(group[read + m + n * stage] * inverse) + 1
                        value = value * 3 + trit
                    low[j + m] = (value * 256 + 242) // 243
                read += 5 * stage
                j += stage

        for h in range(PTQ1_0_HIGH):
            value = 0
            for m in range(4):
                trit = round_half_away(group[read + h + m * PTQ1_0_HIGH] * inverse) + 1
                value = value * 3 + trit
            high[h] = (value * 3 * 256 + 242) // 243

        out += low + high + fp16(scale)
    return bytes(out)


def decode_ptq1_0(packed: bytes) -> list[float]:
    pow3 = (1, 3, 9, 27, 81)
    values: list[float] = []
    for base in range(0, len(packed), PTQ1_0_BYTES):
        block = packed[base : base + PTQ1_0_BYTES]
        scale = struct.unpack("<e", block[PTQ1_0_LOW + PTQ1_0_HIGH :])[0]

        j = 0
        for stage in STAGES:
            while j + stage <= PTQ1_0_LOW:
                for n in range(5):
                    for m in range(stage):
                        shifted = (block[j + m] * pow3[n]) & 0xFF
                        values.append(((shifted * 3) >> 8) - 1)
                j += stage

        for n in range(4):
            for h in range(PTQ1_0_HIGH):
                shifted = (block[PTQ1_0_LOW + h] * pow3[n]) & 0xFF
                values.append(((shifted * 3) >> 8) - 1)

        for i in range(len(values) - GROUP, len(values)):
            values[i] *= scale
    return values


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blocks", type=int, default=2, help="how many 128-weight blocks")
    arguments = parser.parse_args()

    # The same input the C# test builds, so the two can be compared without a fixture file.
    weights = [
        struct.unpack("<f", struct.pack("<f", math.sin(i)))[0]
        for i in range(arguments.blocks * GROUP)
    ]

    pq2_0 = encode_pq2_0(weights)
    ptq1_0 = encode_ptq1_0(weights)

    print(f"w[i] = sin(i), {arguments.blocks} block(s)")
    print()
    print(f"PQ2_0  ({len(pq2_0)} bytes, {len(pq2_0) * 8 / len(weights):.3f} bpw):")
    print(f"  {pq2_0.hex().upper()}")
    print()
    print(f"PTQ1_0 ({len(ptq1_0)} bytes, {len(ptq1_0) * 8 / len(weights):.3f} bpw):")
    print(f"  {ptq1_0.hex().upper()}")
    print()

    decoded = decode_ptq1_0(ptq1_0)
    worst = max(abs(a - b) for a, b in zip(weights, decoded))
    print(f"PTQ1_0 round trip on this (non-ternary) input: max abs error {worst:.4f}")


if __name__ == "__main__":
    main()
